services:
  - type: web
    name: playtv-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: static
    name: playtv-frontend
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist/public
    envVars:
      - key: VITE_API_URL
        value: https://playtv-backend.onrender.com
